language: nix

os:
  - osx
  - linux

script:
  - source nixpkgs/programs/bash/nix.sh
  - mkdir -p ~/.config
  - ln -sfT nixpkgs ~/.config/nixpkgs
  - ls -al ~/.config/nixpkgs/
  - nix-shell '<home-manager>' -A install
